# Create a simple VM

- name: Create a simple VM instance
  hosts: localhost
  connection: local
  gather_facts: no
  
- name: Create a new instance and attaches to a network and passes metadata to the instance
  os_server:
       state: present
       auth:
         #auth_url: https://identity.example.com
         #username: admin
         #password: admin
         project_name: admin
       name: "{{ instance_name }}"
       image: "{{ image }}"
       key_name: "{{ key_name }}"
       timeout: 200
       flavor: "{{ flavor }}"
       nics:
         - net-id: "{{ net-id }}"
         - net-name: "{{ net-name }}"
       meta:
         hostname: test1
         group: uge_master
